"""
Column mapping configurations for various e-commerce platforms.
Maps Korean column names from source files to English database column names.
"""

# 쿠팡 1P 전체 매출 데이터 컬럼 매핑
COLUMN_MAPPING_1P = {
    "날짜": "Date",
    "Product ID": "ID_product_at_sales_report_coupang_1p",
    "바코드": "ID_barcode_at_sales_report_coupang_1p",
    "SKU ID": "ID_product_coupang_1p_at_sales_report_coupang_1p",
    "SKU 명": "Name_product_coupang_1p_at_sales_report_coupang_1p",
    "벤더아이템 ID": "ID_option_coupang_1p_at_sales_report_coupang_1p",
    "벤더아이템명": "Name_option_coupang_1p_at_sales_report_coupang_1p",
    "로켓프레시": "Etc_rocketfresh_at_sales_report_coupang_1p",
    "상품카테고리": "Category_1p_product_coupang_at_sales_report_coupang_1p",
    "하위카테고리": "Category_1p_1_coupang_at_sales_report_coupang_1p",
    "세부카테고리": "Category_1p_2_coupang_at_sales_report_coupang_1p",
    "브랜드": "Name_brand_at_sales_report_coupang_1p",
    "매출액(GMV)": "Sales_GMV_at_sales_report_coupang_1p",
    "판매수량(Units Sold)": "Qty_sales_at_sales_report_coupang_1p",
    "반품수량(Return Units)": "Qty_return_at_sales_report_coupang_1p",
    "매입원가(COGS)": "Price_supply_1p_coupang_at_sales_report_coupang_1p",
    "AMV": "Sales_AMV_at_sales_report_coupang_1p",
    "쿠폰 할인가(쿠팡 추가 할인쿠폰 제외)": "Price_discount_coupon_at_sales_report_coupang_1p",
    "쿠팡 추가 할인쿠폰 할인가": "Price_discount_coupon_extra_at_sales_report_coupang_1p",
    "즉시 할인가": "Price_discount_instant_at_sales_report_coupang_1p",
    "프로모션발생매출액(GMV)": "Sales_promotion_at_sales_report_coupang_1p",
    "프로모션발생판매수량(Units Sold)": "Qty_protmotion_at_sales_report_coupang_1p",
    "평균판매금액(ASP)": "Price_sales_avg_at_sales_report_coupang_1p",
    "주문건수": "Count_order_at_sales_report_coupang_1p",
    "주문 고객 수": "Count_order_cusomer_at_sales_report_coupang_1p",
    "객단가": "Price_per_product_at_sales_report_coupang_1p",
    "구매전환율": "Ratio_CVR_at_sales_report_coupang_1p",
    "PV": "PV_at_sales_report_coupang_1p",
    "정기배송 매출액(SnS GMV)": "Sales_subs_amount_at_sales_report_coupang_1p",
    "정기배송 매입원가(SnS COGS)": "Cost_subs_amount_at_sales_report_coupang_1p",
    "정기배송 비중(SnS %)": "Ratio_subs_sales_at_sales_report_coupang_1p",
    "정기배송 판매수량(SnS Units Sold)": "Qty_subs_sales_at_sales_report_coupang_1p",
    "정기배송 반품수량(Return Units)": "Qty_subs_return_at_sales_report_coupang_1p",
    "상품평 수": "Count_review_at_sales_report_coupang_1p",
    "평균 상품 평점": "Score_review_avg_at_sales_report_coupang_1p",
}

# 쿠팡 2P 전체 매출 데이터 컬럼 매핑
COLUMN_MAPPING_2P = {
    "날짜": "Date",
    "옵션 ID": "ID_option_coupang_2p_at_sales_report_coupang_2p",
    "옵션명": "Name_option_coupang_at_sales_report_coupang_2p",
    "등록상품ID": "ID_product_coupang_2p_at_sales_report_coupang_2p",
    "카테고리": "Category_2p_1_coupang_at_sales_report_coupang_2p",
    "판매방식": "Etc_rocketgrowth_at_sales_report_coupang_2p",
    "매출(원)": "Sales_total_amount_at_sales_report_coupang_2p",
    "주문": "Count_order_at_sales_report_coupang_2p",
    "판매량": "Qty_sales_total_at_sales_report_coupang_2p",
    "조회": "Count_click_at_sales_report_coupang_2p",
    "방문자": "UV_at_sales_report_coupang_2p",
    "장바구니": "Count_cart_at_sales_report_coupang_2p",
    "구매전환율": "Ratio_CVR_at_sales_report_coupang_2p",
    "아이템위너 비율(%)": "Ratio_item_winner_at_sales_report_coupang_2p",
    "총 매출(원)": "Sales_net_amount_at_sales_report_coupang_2p",
    "총 판매수": "Qty_sales_net_at_sales_report_coupang_2p",
    "총 취소 금액": "Sales_cancel_amount_at_sales_report_coupang_2p",
    "총 취소된 상품수": "Qty_cancel_total_at_sales_report_coupang_2p",
    "즉시 취소된 상품수": "Qty_cancel_instant_at_sales_report_coupang_2p"
}

# 쿠팡 매출성장광고 컬럼 매핑
COLUMN_MAPPING_AD = {
    "날짜": "Date",
    "과금방식": "Ad_type_cost_at_ad_report_coupang_by_growth",
    "판매방식": "Sales_type_at_ad_report_coupang_by_growth",
    "광고유형": "Ad_type_at_ad_report_coupang_by_growth",
    "캠페인 ID": "ID_campaign_at_ad_report_coupang_by_growth",
    "캠페인명": "Name_campaign_at_ad_report_coupang_by_growth",
    "광고그룹": "Name_ad_group_at_ad_report_coupang_by_growth",
    "광고집행 상품명": "Name_ad_option_at_ad_report_coupang_by_growth",
    "광고집행 옵션ID": "ID_ad_option_at_ad_report_coupang_by_growth",
    "광고전환매출발생 상품명": "Name_option_conversion_at_ad_report_coupang_by_growth",
    "광고전환매출발생 옵션ID": "ID_option_conversion_at_ad_report_coupang_by_growth",
    "광고 노출 지면": "Retargeting_at_ad_report_coupang_by_growth",
    "키워드": "Keyword_at_ad_report_coupang_by_growth",
    "노출수": "Count_impression_at_ad_report_coupang_by_growth",
    "클릭수": "Count_click_at_ad_report_coupang_by_growth",
    "광고비": "Cost_ad_at_ad_report_coupang_by_growth",
    "클릭률": "Ratio_click_at_ad_report_coupang_by_growth",
    "총 주문수(1일)": "Count_order_total_1d_at_ad_report_coupang_by_growth",
    "직접 주문수(1일)": "Count_order_direct_1d_at_ad_report_coupang_by_growth",
    "간접 주문수(1일)": "Count_order_indirect_1d_at_ad_report_coupang_by_growth",
    "총 판매수량(1일)": "Qty_sales_total_1d_at_ad_report_coupang_by_growth",
    "직접 판매수량(1일)": "Qty_sales_direct_1d_at_ad_report_coupang_by_growth",
    "간접 판매수량(1일)": "Qty_sales_indirect_1d_at_ad_report_coupang_by_growth",
    "총 전환매출액(1일)": "Sales_conversion_total_1d_at_ad_report_coupang_by_growth",
    "직접 전환매출액(1일)": "Sales_conversion_direct_1d_at_ad_report_coupang_by_growth",
    "간접 전환매출액(1일)": "Sales_conversion_indirect_1d_at_ad_report_coupang_by_growth",
    "총 주문수(14일)": "Count_order_total_14d_at_ad_report_coupang_by_growth",
    "직접주문수(14일)": "Count_order_direct_14d_at_ad_report_coupang_by_growth",
    "간접 주문수(14일)": "Count_order_indirect_14d_at_ad_report_coupang_by_growth",
    "총 판매수량(14일)": "Qty_sales_total_14d_at_ad_report_coupang_by_growth",
    "직접 판매수량(14일)": "Qty_sales_direct_14d_at_ad_report_coupang_by_growth",
    "간접 판매수량(14일)": "Qty_sales_indirect_14d_at_ad_report_coupang_by_growth",
    "총 전환매출액(14일)": "Sales_conversion_total_14d_at_ad_report_coupang_by_growth",
    "직접 전환매출액(14일)": "Sales_conversion_direct_14d_at_ad_report_coupang_by_growth",
    "간접 전환매출액(14일)": "Sales_conversion_indirect_14d_at_ad_report_coupang_by_growth",
    "총광고수익률(1일)": "Ratio_ROAS_total_1d_at_ad_report_coupang_by_growth",
    "직접광고수익률(1일)": "Ratio_ROAS_direct_1d_at_ad_report_coupang_by_growth",
    "간접광고수익률(1일)": "Ratio_ROAS_indirect_1d_at_ad_report_coupang_by_growth",
    "총광고수익률(14일)": "Ratio_ROAS_total_14d_at_ad_report_coupang_by_growth",
    "직접광고수익률(14일)": "Ratio_ROAS_direct_14d_at_ad_report_coupang_by_growth",
    "간접광고수익률(14일)": "Ratio_ROAS_indirect_14d_at_ad_report_coupang_by_growth",
    "캠페인 시작일": "Date_campaign_start_at_ad_report_coupang_by_growth",
    "캠페인 종료일": "Date_campaign_end_at_ad_report_coupang_by_growth",
    "비고": "extra"
}

# 쿠팡 첫구매광고 컬럼 매핑
COLUMN_MAPPING_AD_FIRSTBUY = {
    "날짜": "Date",
    "과금방식": "Ad_type_cost_at_ad_report_coupang_by_firstbuy",
    "운영 방식": "Ad_type_auto_at_ad_report_coupang_by_firstbuy",
    "판매방식": "Sales_type_at_ad_report_coupang_by_firstbuy",
    "캠페인 ID": "ID_campaign_at_ad_report_coupang_by_firstbuy",
    "캠페인 이름": "Name_campaign_at_ad_report_coupang_by_firstbuy",
    "캠페인 시작일": "Date_campaign_start_at_ad_report_coupang_by_firstbuy",
    "캠페인 종료일": "Date_campaign_end_at_ad_report_coupang_by_firstbuy",
    "광고 목표": "Ad_type_firstbuy_at_ad_report_coupang_by_firstbuy",
    "노출수": "Count_impression_at_ad_report_coupang_by_firstbuy",
    "클릭수": "Count_click_at_ad_report_coupang_by_firstbuy",
    "클릭률": "Ratio_click_at_ad_report_coupang_by_firstbuy",
    "집행 광고비": "Cost_ad_at_ad_report_coupang_by_firstbuy",
    "동영상 3초 조회": "Count_view_video_3s_at_ad_report_coupang_by_firstbuy",
    "평균 재생 시간": "Count_time_video_avg_at_ad_report_coupang_by_firstbuy",
    "25% 재생수": "Count_view_video_25percent_at_ad_report_coupang_by_firstbuy",
    "50% 재생수": "Count_view_video_50percent_at_ad_report_coupang_by_firstbuy",
    "75% 재생수": "Count_view_video_75percent_at_ad_report_coupang_by_firstbuy",
    "100% 재생수": "Count_view_video_100percent_at_ad_report_coupang_by_firstbuy",
    "동영상 3초 조회당 비용": "Cost_view_video_3s_at_ad_report_coupang_by_firstbuy",
    "참여수": "Count_engagement_at_ad_report_coupang_by_firstbuy",
    "광고그룹 ID": "ID_ad_group_at_ad_report_coupang_by_firstbuy",
    "광고그룹": "Name_ad_group_at_ad_report_coupang_by_firstbuy",
    "광고 ID": "ID_ad_item_at_ad_report_coupang_by_firstbuy",
    "광고 이름": "Name_ad_item_at_ad_report_coupang_by_firstbuy",
    "소재": "Ad_type_video_at_ad_report_coupang_by_firstbuy",
    "광고집행 옵션 ID": "ID_ad_option_at_ad_report_coupang_by_firstbuy",
    "광고집행 상품명": "Name_ad_option_at_ad_report_coupang_by_firstbuy",
    "노출 영역": "Ad_channel_type_at_ad_report_coupang_by_firstbuy",
    "노출된 키워드": "Keyword_by_impression_at_ad_report_coupang_by_firstbuy",
    "소재 영역": "Ad_type_video_detail_at_ad_report_coupang_by_firstbuy",
    "소재 ID": "ID_ad_item_video_at_ad_report_coupang_by_firstbuy",
    "소재 내용": "Name_ad_item_video_at_ad_report_coupang_by_firstbuy",
    "옵션 ID": "ID_option_at_ad_report_coupang_by_firstbuy",
    "상품": "Name_product_ad_option_at_ad_report_coupang_by_firstbuy",
    "랜딩 페이지 유형": "Ad_type_landingpage_at_ad_report_coupang_by_firstbuy",
    "랜딩 페이지 ID": "ID_landingpage_at_ad_report_coupang_by_firstbuy",
    "랜딩 페이지명": "Name_landingpage_at_ad_report_coupang_by_firstbuy"
}

# 카페24 판매 데이터 컬럼 매핑
COLUMN_MAPPING_SALE_OWNED = {
    "날짜": "Date",
    "상품명": "Name_product_at_sales_report_cafe24",
    "노출수": "Count_click_at_sales_report_cafe24",
    "담긴수": "Count_cart_at_sales_report_cafe24",
    "판매건수": "Count_sales_at_sales_report_cafe24",
    "판매물품수": "Qty_sales_at_sales_report_cafe24",
    "판매율": "Ratio_sales_per_cart_at_sales_report_cafe24",
    "판매금액": "Sales_order_at_sales_report_cafe24",
    "담김/노출": "Ratio_cart_per_click_at_sales_report_cafe24",
    "판매/노출": "Ratio_sales_per_click_at_sales_report_cafe24",
    "상품코드": "ID_product_cafe24_at_sales_report_cafe24",
    "자체상품코드": "ID_product_seller_at_sales_report_cafe24",
    "카테고리명(카테고리번호)": "Name_category_at_sales_report_cafe24",
    "카테고리별 판매건수": "Count_sales_by_category_at_sales_report_cafe24",
    "카테고리별 상품판매금액": "Sales_order_by_product_at_sales_report_cafe24"
}

# 네이버 광고 마스터 컬럼 매핑
COLUMN_MAPPING_NAVER_MASTER = {
    "광고주 계정ID": "ID_ad_account_at_ad_ID_daily_update_naver",
    "광고그룹ID": "ID_ad_group_at_ad_ID_daily_update_naver",
    "소재ID": "ID_ad_item_at_ad_ID_daily_update_naver",
    "소재 검토상태": "Confirm_ad_item_at_ad_ID_daily_update_naver",
    "노출여부": "Exposure_or_not_at_ad_ID_daily_update_naver",
    "광고노출 상품명": "Name_ad_item_at_ad_ID_daily_update_naver",
    "소재노출 이미지URL": "URL_ad_item_image_at_ad_ID_daily_update_naver",
    "입찰가": "Price_bid_at_ad_ID_daily_update_naver",
    "광고그룹의 기본입찰가\n사용여부": "Price_bid_default_at_ad_ID_daily_update_naver",
    "네이버 쇼핑 상품정보\n연동여부": "Etc_product_information_link_at_ad_ID_daily_update_naver",
    "소재등록일시": "Date_created_ad_item_at_ad_ID_daily_update_naver",
    "소재삭제일": "Date_deleted_ad_item_at_ad_ID_daily_update_naver",
    "몰 상품ID": "ID_mall_product_at_ad_ID_daily_update_naver",
    "스마트스토어 상품ID": "ID_product_at_ad_ID_daily_update_naver",
    "상품명": "Name_product_at_ad_ID_daily_update_naver",
    "상품이미지 URL": "URL_image_product_at_ad_ID_daily_update_naver",
    "(PC)상품판매페이지 URL": "URL_pc_at_ad_ID_daily_update_naver",
    "(MO)상품판매페이지 URL": "URL_m_at_ad_ID_daily_update_naver",
    "상품가격": "Price_display_at_ad_ID_daily_update_naver",
    "배송비": "Cost_delivery_at_ad_ID_daily_update_naver",
    "카테고리1단계": "Category_1_naver_at_ad_ID_daily_update_naver",
    "카테고리2단계": "Category_2_naver_at_ad_ID_daily_update_naver",
    "카테고리3단계": "Category_3_naver_at_ad_ID_daily_update_naver",
    "카테고리4단계": "Category_4_naver_at_ad_ID_daily_update_naver",
    "카테고리1단계 ID": "ID_category_1_naver_at_ad_ID_daily_update_naver",
    "카테고리2단계 ID": "ID_category_2_naver_at_ad_ID_daily_update_naver",
    "카테고리3단계 ID": "ID_category_3_naver_at_ad_ID_daily_update_naver",
    "카테고리4단계 ID": "ID_category_4_naver_at_ad_ID_daily_update_naver",
    "카테고리 표현 문자열": "Text_category_fullpath_at_ad_ID_daily_update_naver"
}

# 네이버 광고 보고서 컬럼 매핑
COLUMN_MAPPING_NAVER_REPORT = {
    "일별": "Date",
    "캠페인유형": "Ad_campaign_type_at_ad_report_naver_summary",
    "광고그룹유형": "Ad_group_type_at_ad_report_naver_summary",
    "매체이름": "Name_channel_at_ad_report_naver_summary",
    "검색/콘텐츠 매체": "Channel_search_contents_at_ad_report_naver_summary",
    "캠페인": "Name_ad_campaign_at_ad_report_naver_summary",
    "광고그룹": "Name_ad_group_at_ad_report_naver_summary",
    "소재": "ID_ad_item_at_ad_report_naver_summary",
    "노출수": "Count_impression_at_ad_report_naver_summary",
    "클릭수": "Count_click_at_ad_report_naver_summary",
    "클릭률(%)": "Ratio_click_at_ad_report_naver_summary",
    "전환율(%)": "CVR_at_ad_report_naver_summary",
    "전환당비용(원)": "Cost_per_conversion_at_ad_report_naver_summary",
    "광고수익률(%)": "Ratio_ROAS_at_ad_report_naver_summary",
    "총비용(VAT포함,원)": "Cost_ad_at_ad_report_naver_summary",
    "평균클릭비용(VAT포함,원)": "Cost_per_click_avg_at_ad_report_naver_summary",
    "평균노출순위": "Rank_exposure_avg_at_ad_report_naver_summary",
    "전환수": "Count_conversion_at_ad_report_naver_summary",
    "전환수(네이버페이)": "Count_conversion_naverpay_at_ad_report_naver_summary",
    "직접전환수": "Count_conversion_direct_at_ad_report_naver_summary",
    "간접전환수": "Count_conversion_indirect_at_ad_report_naver_summary",
    "전환매출액(원)": "Sales_conversion_at_ad_report_naver_summary",
    "직접전환매출액(원)": "Sales_conversion_direct_at_ad_report_naver_summary",
    "간접전환매출액(원)": "Sales_conversion_indirect_at_ad_report_naver_summary",
    "전환매출액(네이버페이)": "Sales_conversion_naverpay_at_ad_report_naver_summary"
}

# 네이버 오가닉 구매 데이터 컬럼 매핑
COLUMN_MAPPING_NAVER_ORGANIC_PURCHASE = {
    "날짜": "Date",
    "상품카테고리(대)": "Category_1_naver_at_keyword_purchase_report_naver_organic",
    "상품카테고리(중)": "Category_2_naver_at_keyword_purchase_report_naver_organic",
    "상품카테고리(소)": "Category_3_naver_at_keyword_purchase_report_naver_organic",
    "상품카테고리(세)": "Category_4_naver_at_keyword_purchase_report_naver_organic",
    "상품명": "Name_product_at_keyword_purchase_report_naver_organic",
    "상품ID": "ID_product_at_keyword_purchase_report_naver_organic",
    "채널그룹": "Channel_group_at_keyword_purchase_report_naver_organic",
    "채널명": "Channel_name_at_keyword_purchase_report_naver_organic",
    "키워드": "Keyword_at_keyword_purchase_report_naver_organic",
    "결제수": "Count_order_14d_at_keyword_purchase_report_naver_organic",
    "결제금액": "Sales_order_14d_at_keyword_purchase_report_naver_organic"
}

# 네이버 기타 매출 데이터 컬럼 매핑
COLUMN_MAPPING_SALES_REPORT_NAVER_ETC = {
    "날짜": "Date",
    "상품카테고리(대)": "Category_1_naver_at_sales_report_naver_etc",
    "상품카테고리(중)": "Category_2_naver_at_sales_report_naver_etc",
    "상품카테고리(소)": "Category_3_naver_at_sales_report_naver_etc",
    "상품카테고리(세)": "Category_4_naver_at_sales_report_naver_etc",
    "상품명": "Name_product_at_sales_report_naver_etc",
    "상품ID": "ID_product_at_sales_report_naver_etc",
    "채널그룹": "Channel_group_at_sales_report_naver_etc",
    "채널명": "Channel_name_at_sales_report_naver_etc",
    "채널상세": "Channel_detail_at_sales_report_naver_etcc",
    "결제수": "Count_order_14d_at_sales_report_naver_etc",
    "결제금액": "Sales_order_14d_at_sales_report_naver_etc"
}

# 네이버 오가닉 클릭 데이터 컬럼 매핑
COLUMN_MAPPING_NAVER_ORGANIC_CLICK = {
    "날짜": "Date",
    "상품카테고리(대)": "Category_1_naver_at_keyword_click_report_naver_organic",
    "상품카테고리(중)": "Category_2_naver_at_keyword_click_report_naver_organic",
    "상품카테고리(소)": "Category_3_naver_at_keyword_click_report_naver_organic",
    "상품카테고리(세)": "Category_4_naver_at_keyword_click_report_naver_organic",
    "상품명": "Name_product_at_keyword_click_report_naver_organic",
    "상품ID": "ID_product_at_keyword_click_report_naver_organic",
    "채널그룹": "Name_channel_group_at_keyword_click_report_naver_organic",
    "채널명": "Name_channel_at_keyword_click_report_naver_organic",
    "키워드": "Keyword_at_keyword_click_report_naver_organic",
    "평균노출순위": "Rank_exposure_avg_at_keyword_click_report_naver_organic",
    "유입수": "Count_click_at_keyword_click_report_naver_organic"
}
